let base = [ // pozitii ca in specificatie
	'morcov dulce',
	'morcov iute',
	'morcov picant',
	'sfecla picanta',
	'telina picanta',
	'"sanatate"',
	'conopida marinate',
	'varza de mare',
	'vinata delicioasa',
	'vinata picanta',
	'vinata tocata',
	'asorti de varza picant',
	'adjica delicioasa', 
	'tomate picante marinate',
	'tomate murate',
	'rosii murate verzi',
	'castraveti murati',
	'cornisoni murati',
	'castraveti murati procesati',
	'varza murata',
	'ardei umpluti',
	'morcov dulce top',
	'morcov iute top',
	'morcov picant top',
	'varza murata top',
	'harbuz murati',
];
let pos = [ // gramaj ca in specificatie
	'200g',
	'400g',
	'1000g',
	'600g',
	'(VID) 500g',
	'500g',
];
